name: DiscordReport
version: ${project.version}
main: io.github.jefflegendpower.discordreport.DiscordReport
api-version: 1.16
authors: [ JeffLegendPower ]
commands:
  report:
    description: Reports players to discord
    usage: /report

